name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install
    - run: npm test
    - run: npm run build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

